### ISSUE TITLE
default tint2 theme

### ISSUE THREAD

**Issue by joksik** [ARCHLabs/Archlabs-Tint2-Themes#1]
Hello i use latest archlabs 4.1 there is 2 defaults files for tint2 but unfortunately they are dont show battery status for laptop. what i must change in this file to show battery status?

**Comment by Dobbie03** [comment]
You can install this:
https://github.com/ARCHLabs/fdpowermon

**Comment by natemaia** [comment]
Battery support has been added to all themes in our repo. 
You can dowload them, or wait for next release where it will be standard
